/* AUTO-GENERATED by build-brain-data.js on 2026-07-15T16:06:33.706Z - never hand-edit */
window.BRAIN_DATA = {
 "generated": "2026-07-15T16:06:33.706Z",
 "clusters": [
  {
   "id": "web",
   "name": "Web / Build",
   "color": "#5B9DFF"
  },
  {
   "id": "seo",
   "name": "SEO & AI visibility",
   "color": "#2DD4BF"
  },
  {
   "id": "sales",
   "name": "Sales / Growth",
   "color": "#F5A623"
  },
  {
   "id": "strategy",
   "name": "Strategy / Consultancy",
   "color": "#A78BFA"
  },
  {
   "id": "content",
   "name": "Content / Creative",
   "color": "#F472B6"
  },
  {
   "id": "ads",
   "name": "Paid ads",
   "color": "#F06A6A"
  },
  {
   "id": "systems",
   "name": "Systems / Ops",
   "color": "#4ADE80"
  },
  {
   "id": "intel",
   "name": "Intelligence / Memory",
   "color": "#C9D4E8"
  }
 ],
 "skills": [
  {
   "name": "banner-design",
   "desc": "Design banners for social media, ads, website heroes, creative assets, and print. Multiple art direction options with AI-generated visuals. Actions: design, create, generate banner. Platforms: Facebook, Twitter/X, LinkedIn, YouTube, Instagram, Google Display, website hero, print. Styles: minimalist, gradient, bold typo",
   "cluster": "content",
   "src": "local",
   "mtime": "2026-07-01",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-anti-ai-tells",
   "desc": "The BB catalogue of visual cliches that make a design look AI-generated, and the rule to never ship them. ALWAYS activate on any Business Booster SYSTEM or WEBSITE build, redesign, reskin, polish, or design review (auto-loads alongside bb-web-master and bb-systems-master). Trigger whenever anyone builds/fixes/styles a ",
   "cluster": "systems",
   "src": "local",
   "mtime": "2026-07-15",
   "depth": 0,
   "latest": null,
   "trigger": "looks AI",
   "quiet": false
  },
  {
   "name": "bb-backlink-engine",
   "desc": "The BB off-page authority engine - backlinks, local citations, OTA profiles, unlinked mentions, and digital PR for any client, run as a pipeline. ALWAYS activate when the work is earning links or authority for a client site - \"backlinks\", \"link building\", \"off-page SEO\", \"citations\", \"get us mentioned\", \"domain authori",
   "cluster": "seo",
   "src": "local",
   "mtime": "2026-07-14",
   "depth": 0,
   "latest": null,
   "trigger": "backlinks",
   "quiet": false
  },
  {
   "name": "bb-blog-engine",
   "desc": "The BB Client Blog Formula - the end-to-end engine that takes any client from cold start to ranking, AI-cited blog content. ALWAYS activate when planning blog SEO for a client, building a content cluster, deciding what blog posts to write, setting publishing cadence, measuring blog/organic performance, refreshing old p",
   "cluster": "seo",
   "src": "local",
   "mtime": "2026-07-14",
   "depth": 0,
   "latest": null,
   "trigger": "blog plan",
   "quiet": false
  },
  {
   "name": "bb-blog-pack-builder",
   "desc": "The Business Booster blog-PACK deliverable builder — turns a client BRAIN + a reference format into a set of publish-ready SEO + AEO + GEO blog posts, rated to a 9/10 gate, rendered as one branded PDF. ALWAYS activate when the ask is to PRODUCE a batch of client blog articles as a deliverable: \"make N blog posts\", \"wri",
   "cluster": "content",
   "src": "local",
   "mtime": "2026-07-13",
   "depth": 1,
   "latest": {
    "date": "2026-07-13",
    "summary": "Sapphire Trails, 8-post SEO/AEO/GEO pack (first build)"
   },
   "trigger": "make N blog posts",
   "quiet": false
  },
  {
   "name": "bb-competitor-analysis",
   "desc": ">-",
   "cluster": "strategy",
   "src": "local",
   "mtime": "2026-07-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-consultancy-master",
   "desc": "The Business Booster master consultancy engine and conductor. ALWAYS activate for ANY client strategy, consultancy, audit, or full-company-breakdown work — building a Client Brain, ICP, competitor analysis, SEO audit, GEO/AI-search report, website/CRO consultancy, marketing strategy, digital marketing strategy, content",
   "cluster": "strategy",
   "src": "local",
   "mtime": "2026-07-07",
   "depth": 0,
   "latest": null,
   "trigger": "full breakdown",
   "quiet": false
  },
  {
   "name": "bb-content-plan-builder",
   "desc": "The Business Booster content-plan deliverable builder. ALWAYS activate whenever the work is producing a monthly (or weekly) social CONTENT PLAN document for a client — the branded post-by-post deck with each graphic, its caption, hashtags, contact block and pillar tag, exported as a share-ready PDF and a Canva-friendly",
   "cluster": "content",
   "src": "local",
   "mtime": "2026-07-11",
   "depth": 3,
   "latest": {
    "date": "2026-07-11",
    "summary": "Fixing baked-in text on raster graphics (SAPHIRE -> SAPPHIRE, 11 images)"
   },
   "trigger": "content plan",
   "quiet": false
  },
  {
   "name": "bb-content-strategy",
   "desc": ">-",
   "cluster": "strategy",
   "src": "local",
   "mtime": "2026-07-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-cro-strategy",
   "desc": ">-",
   "cluster": "web",
   "src": "local",
   "mtime": "2026-07-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-customer-retention",
   "desc": ">-",
   "cluster": "sales",
   "src": "local",
   "mtime": "2026-07-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-deck-builder",
   "desc": "BB's standard for building SEND-READY client decks and PDFs (PowerPoint or PDF) that need ZERO Canva edits. ALWAYS activate when building, generating, or exporting any deck, slide, presentation, ICP, pitch, proposal, one-pager, packages sheet, report, or branded PDF for Business Booster or a BB client - anything the cl",
   "cluster": "content",
   "src": "local",
   "mtime": "2026-07-15",
   "depth": 5,
   "latest": {
    "date": "2026-07-15",
    "summary": "REAL LOGOS, not typed names (Waverley ICP)"
   },
   "trigger": "building, generating, or exporting any deck, slide, presentation, ICP, pitch, pr",
   "quiet": false
  },
  {
   "name": "bb-digital-marketing-strategy",
   "desc": ">-",
   "cluster": "strategy",
   "src": "local",
   "mtime": "2026-07-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-ditto",
   "desc": ">",
   "cluster": "systems",
   "src": "local",
   "mtime": "2026-07-12",
   "depth": 2,
   "latest": {
    "date": "2026-07-10",
    "summary": "playzone-marketing-dna.md (marketing domain, from the real Jun-2026 scan) - the"
   },
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-elevate",
   "desc": ">",
   "cluster": "systems",
   "src": "local",
   "mtime": "2026-07-10",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-fable-mind",
   "desc": ">",
   "cluster": "intel",
   "src": "local",
   "mtime": "2026-07-12",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-geo-master",
   "desc": ">-",
   "cluster": "seo",
   "src": "local",
   "mtime": "2026-07-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-google-ads-expert",
   "desc": ">",
   "cluster": "ads",
   "src": "local",
   "mtime": "2026-07-10",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-growth-sales",
   "desc": ">",
   "cluster": "sales",
   "src": "local",
   "mtime": "2026-07-06",
   "depth": 6,
   "latest": {
    "date": "2026-07-04",
    "summary": "Leon/BSWL — the service-to-system upsell ladder is real"
   },
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-lifecycle-crm",
   "desc": ">-",
   "cluster": "sales",
   "src": "local",
   "mtime": "2026-07-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-measurement-analytics",
   "desc": ">-",
   "cluster": "strategy",
   "src": "local",
   "mtime": "2026-07-13",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-meta-ads-copilot",
   "desc": ">",
   "cluster": "ads",
   "src": "local",
   "mtime": "2026-07-10",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-meta-ads-expert-plus",
   "desc": ">",
   "cluster": "ads",
   "src": "local",
   "mtime": "2026-07-10",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-mother-brain",
   "desc": ">-",
   "cluster": "intel",
   "src": "local",
   "mtime": "2026-07-03",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-motion-master",
   "desc": "The Business Booster premium WEB-ANIMATION brain — cinematic, Awwwards-tier scroll-driven websites. ALWAYS activate when a BB website needs to feel premium/cinematic/alive at the PAGE level — scroll-driven hero sections, parallax, image mask reveals, kinetic typography (word-by-word headline reveals, underline draws, a",
   "cluster": "web",
   "src": "local",
   "mtime": "2026-07-04",
   "depth": 4,
   "latest": {
    "date": "2026-07-06",
    "summary": "All 5 BB industry templates shipped: ONE motion substrate, 5 art directions"
   },
   "trigger": "a BB website needs to feel premium/cinematic/alive at the PAGE level — scroll-dr",
   "quiet": false
  },
  {
   "name": "bb-quality-gate",
   "desc": ">",
   "cluster": "systems",
   "src": "local",
   "mtime": "2026-07-12",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-sales-strategy",
   "desc": ">",
   "cluster": "sales",
   "src": "local",
   "mtime": "2026-07-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-say-it-out-loud",
   "desc": ">",
   "cluster": "content",
   "src": "local",
   "mtime": "2026-07-14",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-seo-geo-blog-plus",
   "desc": "The BB per-post ranking layer that rides ON TOP of bb-seo-geo-blog for every blog post. ALWAYS activate alongside bb-seo-geo-blog whenever writing, editing, or refreshing any blog post or article for any client. Adds what the base skill lacks - emitted JSON-LD structured data (Article, FAQPage, BreadcrumbList, author P",
   "cluster": "seo",
   "src": "local",
   "mtime": "2026-07-13",
   "depth": 0,
   "latest": null,
   "trigger": "write a blog post",
   "quiet": false
  },
  {
   "name": "bb-seo-master",
   "desc": ">-",
   "cluster": "seo",
   "src": "local",
   "mtime": "2026-07-14",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-strategy-synthesizer",
   "desc": ">-",
   "cluster": "strategy",
   "src": "local",
   "mtime": "2026-07-03",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-system-forge",
   "desc": "The BB client-system factory protocol. ALWAYS activate when Thulaib asks to build, scope, quote, or onboard a NEW client system — CRM, leads system, sales system, booking system, or any \"make a system for [client/company]\" request. Triggers include \"new system for\", \"client wants a system\", \"build them a CRM\", \"onboard",
   "cluster": "systems",
   "src": "local",
   "mtime": "2026-07-10",
   "depth": 21,
   "latest": {
    "date": "2026-07-10",
    "summary": "RESTAURANT VERTICAL MOLD BUILT (archetype 3, on Fable)"
   },
   "trigger": "new system for",
   "quiet": false
  },
  {
   "name": "bb-systemization",
   "desc": ">-",
   "cluster": "strategy",
   "src": "local",
   "mtime": "2026-07-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-tiktok-ads-expert",
   "desc": ">",
   "cluster": "ads",
   "src": "local",
   "mtime": "2026-07-10",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-vertical-blueprint",
   "desc": ">",
   "cluster": "systems",
   "src": "local",
   "mtime": "2026-07-10",
   "depth": 2,
   "latest": {
    "date": "2026-07-10",
    "summary": "restaurant — first blueprint (method proof run)"
   },
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-web-master",
   "desc": "The Business Booster master web developer brain. ALWAYS activate for ANY website or web app work for Business Booster — building, fixing, redesigning, or deploying sites, landing pages, web apps, dashboards, demos, or BB internal systems (Command Centre, SMM, Video, Graphic, Leads), and client websites. Trigger wheneve",
   "cluster": "web",
   "src": "local",
   "mtime": "2026-07-15",
   "depth": 143,
   "latest": {
    "date": "2026-07-15",
    "summary": "ELEVATED bb-web-seo-foundation (Fable) + Sastho proof retrofit: THE SUBPATH TRAP and THE WHATSAPP STANDARD"
   },
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-web-seo-foundation",
   "desc": "The mandatory SEO + AEO + GEO foundation baked into EVERY Business Booster website from day one. ALWAYS activate on any website or landing page build, rebuild, retrofit, or template for a BB client (loaded automatically by bb-web-master STEP 0). Makes the site rank-ready on Google (SEO), answer-box-ready (AEO), citable",
   "cluster": "seo",
   "src": "local",
   "mtime": "2026-07-15",
   "depth": 0,
   "latest": null,
   "trigger": "make a website",
   "quiet": false
  },
  {
   "name": "brand",
   "desc": "Brand voice, visual identity, messaging frameworks, asset management, brand consistency. Activate for branded content, tone of voice, marketing assets, brand compliance, style guides.",
   "cluster": "content",
   "src": "local",
   "mtime": "2026-07-01",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "design",
   "desc": "Comprehensive design skill: brand identity, design tokens, UI styling, logo generation (55 styles, Gemini AI), corporate identity program (50 deliverables, CIP mockups), HTML presentations (Chart.js), banner design (22 styles, social/ads/web/print), icon design (15 styles, SVG, Gemini 3.1 Pro), social photos (HTML→scre",
   "cluster": "content",
   "src": "local",
   "mtime": "2026-07-01",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "design-system",
   "desc": "Token architecture, component specifications, and slide generation. Three-layer tokens (primitive→semantic→component), CSS variables, spacing/typography scales, component specs, strategic slide creation. Use for design tokens, systematic design, brand-compliant presentations.",
   "cluster": "content",
   "src": "local",
   "mtime": "2026-07-01",
   "depth": 0,
   "latest": null,
   "trigger": "design tokens, systematic design, brand-compliant presentations",
   "quiet": false
  },
  {
   "name": "slides",
   "desc": "Create strategic HTML presentations with Chart.js, design tokens, responsive layouts, copywriting formulas, and contextual slide strategies.",
   "cluster": "content",
   "src": "local",
   "mtime": "2026-07-01",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "ui-styling",
   "desc": "Create beautiful, accessible user interfaces with shadcn/ui components (built on Radix UI + Tailwind), Tailwind CSS utility-first styling, and canvas-based visual designs. Use when building user interfaces, implementing design systems, creating responsive layouts, adding accessible components (dialogs, dropdowns, forms",
   "cluster": "web",
   "src": "local",
   "mtime": "2026-07-01",
   "depth": 0,
   "latest": null,
   "trigger": "building user interfaces, implementing design systems, creating responsive layou",
   "quiet": false
  },
  {
   "name": "ui-ux-pro-max",
   "desc": "UI/UX design intelligence for web and mobile. Includes 50+ styles, 161 color palettes, 57 font pairings, 161 product types, 99 UX guidelines, and 25 chart types across 10 stacks (React, Next.js, Vue, Svelte, SwiftUI, React Native, Flutter, Tailwind, shadcn/ui, and HTML/CSS). Actions: plan, build, create, design, implem",
   "cluster": "web",
   "src": "local",
   "mtime": "2026-07-01",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-ads-strategy",
   "desc": "The Business Booster Paid Advertising Strategy skill. Activates whenever any conversation involves paid ads, boosting, Meta Ads, TikTok Ads, Google Ads, ad budgets, campaign strategy, audience targeting, retargeting, ad creative, or when advising a client on whether to boost content. Also activates when discussing BB's",
   "cluster": "ads",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "discussing BB's upsell from organic to paid, when a client asks why their booste",
   "quiet": false
  },
  {
   "name": "bb-ai-prompt-master",
   "desc": "The Business Booster AI Prompt Master skill. Activates whenever anyone needs to generate a prompt for AI image or video generation for any BB client or internal use. Use this skill when anyone says: \"write me a prompt\", \"generate a prompt\", \"AI image prompt\", \"Sora prompt\", \"Gemini prompt\", \"image generation\", \"video p",
   "cluster": "intel",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "write me a prompt",
   "quiet": false
  },
  {
   "name": "bb-analytics-reporting",
   "desc": "The Business Booster Analytics and Reporting skill. Activates whenever a conversation involves reading or interpreting social media analytics, building or presenting a monthly report, tracking client KPIs, assessing content performance, identifying what is and isn't working on a client account, preparing for a retentio",
   "cluster": "strategy",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "asked what metrics to track, how to read Instagram or Facebook insights, how to",
   "quiet": false
  },
  {
   "name": "bb-brain",
   "desc": "The Business Booster master intelligence. Activates for all BB strategy, client, content, sales and operations work. Makes Claude respond as a 25-year veteran who knows BB inside out.",
   "cluster": "intel",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-canva-edits",
   "desc": ">",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-24",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-caption-writer",
   "desc": "Writes social media captions for Business Booster clients. Activates when asked to write a caption, post copy or social media content for any client.",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "write a caption, post copy or social media content for any client",
   "quiet": false
  },
  {
   "name": "bb-client-brain",
   "desc": ">",
   "cluster": "intel",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-client-retention",
   "desc": "The Business Booster Client Retention skill. Activates whenever a conversation involves keeping a client, handling a client who wants to pause or cancel, preparing for a renewal conversation, upgrading a client from one package to another, managing a client complaint, dealing with a client who says they're not seeing r",
   "cluster": "sales",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "discussing client health, satisfaction, MRR protection, or any situation where a",
   "quiet": false
  },
  {
   "name": "bb-code-review",
   "desc": "The Business Booster Code Review skill. ALWAYS activate before any BB-built code is shipped, pushed to GitHub, or shared with anyone. This skill runs a structured code quality check across logic, security, performance, accessibility, and mobile — catching bugs and vulnerabilities before real users find them. Trigger wh",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-06-08",
   "depth": 0,
   "latest": null,
   "trigger": "review this code",
   "quiet": false
  },
  {
   "name": "bb-content-planning",
   "desc": "The Business Booster Content Planning skill. Activates whenever a conversation involves building a monthly content calendar, planning 30 days of content for a client, deciding how many posts vs videos vs stories to schedule, balancing content objectives across a month, planning content around Sri Lanka local events and",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "asked how to plan a content month, what the content mix should be, or how to seq",
   "quiet": false
  },
  {
   "name": "bb-deck-review",
   "desc": ">",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-24",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-digital-marketing-fundamentals",
   "desc": "The Business Booster Digital Marketing Fundamentals skill. Activates whenever a conversation involves digital marketing strategy, marketing funnels, organic vs paid marketing, content marketing, brand building, marketing ROI, customer journey, lead generation, conversion strategy, marketing budgets, or any foundational",
   "cluster": "strategy",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "t understand why followers don",
   "quiet": false
  },
  {
   "name": "bb-editor-brief",
   "desc": ">",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-feature-scoper",
   "desc": "The Business Booster Feature Scoper skill. Activates whenever a new feature is requested for any existing BB tool — before any code is written. This skill forces proper requirements gathering, catches edge cases early, and prevents half-built features that break existing functionality. ALWAYS trigger when anyone says: ",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-06-08",
   "depth": 0,
   "latest": null,
   "trigger": "can we add",
   "quiet": false
  },
  {
   "name": "bb-ghostwriter-personal",
   "desc": ">",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-graphic-brief",
   "desc": ">",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-icp-builder",
   "desc": "Builds a complete Ideal Customer Profile for any BB client. Use when starting a new client, building a strategy or defining the target audience.",
   "cluster": "strategy",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "starting a new client, building a strategy or defining the target audience",
   "quiet": false
  },
  {
   "name": "bb-meta-ads-expert",
   "desc": "The Business Booster Meta Ads Expert skill. Activates whenever any conversation involves Meta advertising in any form — boosting posts, Facebook Ads Manager, Instagram ads, campaign setup, audience targeting, ad creative decisions, budget allocation, ROAS, pixel setup, campaign structure, ad account organisation, under",
   "cluster": "ads",
   "src": "plugin",
   "mtime": "2026-06-16",
   "depth": 0,
   "latest": null,
   "trigger": "a client asks why their ads aren't working, when planning a Meta ad strategy for",
   "quiet": false
  },
  {
   "name": "bb-motion",
   "desc": "The Business Booster Motion and Animation skill. ALWAYS activate this skill before adding any animation, transition, hover effect, scroll effect, loading sequence, or any form of movement to any BB visual deliverable — HTML artifacts, React components, dashboards, the BB Command Centre, the Inspo Hub, client websites, ",
   "cluster": "web",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "add animation",
   "quiet": false
  },
  {
   "name": "bb-onboarding",
   "desc": "The Business Booster Client Onboarding skill. Activates whenever a conversation involves onboarding a new client, the steps after a client signs, what happens in the first week, what documents to collect, how to run the first strategy session, how to set client expectations in Month 1, the internal handover from CEO to",
   "cluster": "sales",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "training a PM or SMM on the onboarding process, when a new client asks what happ",
   "quiet": false
  },
  {
   "name": "bb-pitch-deck-builder",
   "desc": "The Business Booster Pitch Deck Builder skill. Activates whenever anyone needs to build a sales pitch deck to win a new BB client or expand an existing one. Use this skill when anyone says: 'build a pitch deck for [client]', 'create a pitch for [prospect]', 'I need a deck for my meeting', 'pitch deck', 'sales deck', 'p",
   "cluster": "sales",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "build a pitch deck for [client]",
   "quiet": false
  },
  {
   "name": "bb-polish",
   "desc": "The Business Booster UI and Design Polish skill. Activates whenever any visual deliverable — HTML artifact, React component, slide deck, dashboard, web page, graphic brief, or any user interface — needs to be reviewed, tightened, or elevated to BB quality standard before delivery. ALWAYS activate this skill when: (1) t",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "polish",
   "quiet": false
  },
  {
   "name": "bb-post-formulas",
   "desc": ">",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-prospecting",
   "desc": "The Business Booster Prospecting skill. Activates whenever anyone needs to find new clients, build a lead list, research a prospect before a call, identify buying signals on a business's social media, plan outreach campaigns, or decide which businesses to target in Sri Lanka. Also activates when asked: \"who should I ca",
   "cluster": "sales",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "who should I call this week",
   "quiet": false
  },
  {
   "name": "bb-psychology",
   "desc": "The Business Booster Audience Psychology Layer. Activates for ALL BB content work — scripts, captions, posts, videos, ICPs, strategy plans and client briefs. Use this skill whenever the conversation involves: audience psychology, awareness stages, emotional triggers, content objective setting, why a piece of content sh",
   "cluster": "strategy",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "select a formula, write a hook, plan a content month, or assess why content is n",
   "quiet": false
  },
  {
   "name": "bb-quality-standards",
   "desc": "The Business Booster Quality Standards skill. ALWAYS activate this skill before producing ANY visual deliverable for a BB client — one-pagers, content rules and guardrails docs, content plans, graphic briefs, video briefs, monthly reports, ICP docs, competitor analyses, strategy plans, slide decks, or any PPT, PDF or p",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "build the [doc] for [client]",
   "quiet": false
  },
  {
   "name": "bb-reporting-accuracy",
   "desc": ">",
   "cluster": "strategy",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-sales-playbook",
   "desc": "The Business Booster Sales Playbook skill. Activates whenever any conversation involves sales, prospecting, cold calling, cold emailing, lead generation, follow-up sequences, objection handling, closing a deal, pitching BB services, qualifying a prospect, or preparing for a sales meeting or discovery call. Also activat",
   "cluster": "sales",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "too expensive",
   "quiet": false
  },
  {
   "name": "bb-script-intelligence",
   "desc": "The Business Booster Script Intelligence Layer. Activates alongside bb-script-system for every video script request. Runs the strategic pre-writing thinking BEFORE the 3-document output is produced — so every script is built on a locked foundation, not assumptions. Adds 7 capabilities missing from the base script syste",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-script-system",
   "desc": "Writes video scripts for Business Booster clients in the exact 3-document format — Script, Editor Brief and Publishing Brief. Activates whenever a video script or content brief is requested.",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-seo-geo-blog",
   "desc": "The Business Booster SEO and GEO Blog Writer skill. Activates whenever a blog post needs to be written for any BB client. Combines 25 years of SEO expertise with Generative Engine Optimisation (GEO) principles to produce blog posts that rank on Google AND get cited by AI models like ChatGPT, Gemini and Claude. Always l",
   "cluster": "seo",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-seo-knowledge",
   "desc": "The Business Booster SEO Knowledge skill. Activates whenever a conversation involves search engine optimisation, Google rankings, website traffic, on-page SEO, technical SEO, local SEO, Google Business Profile, keyword research, backlinks, meta tags, page speed, Core Web Vitals, or any question about how to make a webs",
   "cluster": "seo",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "t showing on Google, when scoping or explaining BB",
   "quiet": false
  },
  {
   "name": "bb-slide-presenter",
   "desc": "The Business Booster Frontend Presentation Slide skill. Activates whenever anyone asks to build an interactive presentation, a slide deck that runs in the browser, a pitch deck as a web artifact, a client-facing presentation in HTML or React, or any slide-based visual that needs to be shown on screen during a meeting. ",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "build me slides",
   "quiet": false
  },
  {
   "name": "bb-smm-agent",
   "desc": ">",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-system-debug",
   "desc": "BB System Debug Protocol. Activates whenever there is a bug, error or issue with any BB internal system — Command Centre, SMM Workspace, GD Workspace, or any other BB-built tool. Runs a structured diagnostic before touching any code. NEVER guess. NEVER patch blindly. Always get the console log and live file first.",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-systems-architect",
   "desc": "The Business Booster Systems Architecture skill. ALWAYS activate this skill before building ANY new BB tool, system, dashboard, workspace, hub, or web application — no matter how small it seems. This skill forces structured architecture thinking before a single line of code is written, preventing rebuilds, broken flows",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-06-08",
   "depth": 0,
   "latest": null,
   "trigger": "build a system",
   "quiet": false
  },
  {
   "name": "bb-systems-master",
   "desc": "The BB Systems Master Intelligence. ALWAYS activate this skill for ANY work on BB internal systems — Command Centre, Video System, Leads System, SMM Workspace, GD Workspace, or any new BB tool. Contains the complete architecture, database schemas, design system, build rules, interconnection map, and technical debt regi",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-06-29",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-token-saver",
   "desc": ">",
   "cluster": "intel",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-trainer",
   "desc": ">",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-typography",
   "desc": "The Business Booster Typography System skill. ALWAYS activate this skill before producing or reviewing any visual deliverable that contains text — HTML artifacts, React components, dashboards, slide decks, Word documents, PDFs, client one-pagers, reports, or any interface where text appears. Trigger whenever anyone say",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "the text looks wrong",
   "quiet": false
  },
  {
   "name": "bb-ux-audit",
   "desc": "The Business Booster UX Audit skill. Activates whenever any BB tool, system, dashboard, workspace, or web page needs to be reviewed for user experience quality. ALWAYS activate before declaring any build \"done\" or \"ready to ship\". Also activates when the user says: \"something feels off\", \"this doesn't feel right\", \"aud",
   "cluster": "strategy",
   "src": "plugin",
   "mtime": "2026-06-08",
   "depth": 0,
   "latest": null,
   "trigger": "done",
   "quiet": false
  },
  {
   "name": "bb-video-formulas",
   "desc": ">",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-video-viral-expert",
   "desc": "Activates for all video content, scripts, hooks, viral strategy and creative direction work. Makes Claude respond as a 25-year veteran videographer, editor, scriptwriter and digital marketing expert who knows how to make content go viral and generate revenue.",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-visual-qa",
   "desc": ">",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "bb-writing-style",
   "desc": "Controls how Claude writes for Business Booster — tone, formatting and style preferences.",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "consolidate-memory",
   "desc": "Reflective pass over your memory files — merge duplicates, fix stale facts, prune the index.",
   "cluster": "intel",
   "src": "plugin",
   "mtime": "2026-07-15",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "docx",
   "desc": "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files) or Word templates (.dotx files). Triggers include: any mention of 'Word doc', 'word document', '.docx', '.dotx', or requests to produce professional documents with formatting like tables of contents, headings, page ",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-07-11",
   "depth": 0,
   "latest": null,
   "trigger": "Word doc",
   "quiet": false
  },
  {
   "name": "pdf",
   "desc": "Use this skill whenever the user wants to do anything with PDF files. This includes reading or extracting text/tables from PDFs, combining or merging multiple PDFs into one, splitting PDFs apart, rotating pages, adding watermarks, creating new PDFs, filling PDF forms, encrypting/decrypting PDFs, extracting images, and ",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-07-11",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "pdf-reading",
   "desc": "Use this skill when you need to read, inspect, or extract content from PDF files — especially when file content is NOT in your context and you need to read it from disk. Covers content inventory, text extraction, page rasterization for visual inspection, embedded image/attachment/table/form-field extraction, and choosi",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "you need to read, inspect, or extract content from PDF files — especially when f",
   "quiet": false
  },
  {
   "name": "pptx",
   "desc": "Use this skill any time a .pptx or .potx file is involved in any way — as input, output, or both. This includes: creating slide decks, pitch decks, or presentations; reading, parsing, or extracting text from any .pptx or .potx file (even if the extracted content will be used elsewhere, like in an email or summary); edi",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-07-11",
   "depth": 0,
   "latest": null,
   "trigger": "deck,\\",
   "quiet": false
  },
  {
   "name": "schedule",
   "desc": "Create or update a scheduled task that runs automatically. Use when the user says things like \\\"every day\\\", \\\"each morning\\\", \\\"remind me in an hour\\\", \\\"run this at noon\\\", or wants to reschedule an existing task.",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-07-15",
   "depth": 0,
   "latest": null,
   "trigger": "every day\\",
   "quiet": false
  },
  {
   "name": "setup-cowork",
   "desc": "Guided Cowork setup — install role-matched plugins, connect your tools, try a skill.",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-07-15",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "skill-creator",
   "desc": "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, edit, or optimize an existing skill, run evals to test a skill, benchmark skill performance with variance analysis, or optimize a skill's description for better triggering accuracy.",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-07-15",
   "depth": 0,
   "latest": null,
   "trigger": "users want to create a skill from scratch, edit, or optimize an existing skill,",
   "quiet": false
  },
  {
   "name": "video-project-manager-template",
   "desc": "Scaffold a complete video/creative production project management system for a new company. Based on the BB Graphics Video Pro Tool — includes pipeline board, client management, task tracking, time logging, analytics, team management, file attachments, and categorised links. Use this skill when asked to build, clone, or",
   "cluster": "systems",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "asked to build, clone, or set up a new instance of the production management sys",
   "quiet": false
  },
  {
   "name": "webdev-animation",
   "desc": ">",
   "cluster": "web",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "webdev-cms",
   "desc": ">",
   "cluster": "web",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "webdev-database",
   "desc": ">",
   "cluster": "web",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "webdev-master",
   "desc": ">",
   "cluster": "web",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "webdev-mobile",
   "desc": ">",
   "cluster": "web",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "webdev-nextjs",
   "desc": ">",
   "cluster": "web",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "webdev-performance",
   "desc": ">",
   "cluster": "web",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "webdev-rbac-permission-fix",
   "desc": "Workflow for auditing and fixing role-based access control (RBAC) permission gaps in a tRPC + React webdev project. Use when managers or other non-admin roles cannot see UI controls (buttons, menus, filters) that should be available to them; a new role needs to be granted the same UI access as admins for specific opera",
   "cluster": "web",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "managers or other non-admin roles cannot see UI controls (buttons, menus, filter",
   "quiet": false
  },
  {
   "name": "webdev-react",
   "desc": ">",
   "cluster": "web",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "webdev-seo",
   "desc": ">",
   "cluster": "seo",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "webdev-wordpress-handoff",
   "desc": ">",
   "cluster": "web",
   "src": "plugin",
   "mtime": "2026-06-07",
   "depth": 0,
   "latest": null,
   "trigger": "",
   "quiet": false
  },
  {
   "name": "xlsx",
   "desc": "Use this skill any time a spreadsheet file is the primary input or output. This means any task where the user wants to: open, read, edit, or fix an existing .xlsx, .xlsm, .xltx, .csv, or .tsv file (e.g., adding columns, computing formulas, formatting, charting, cleaning messy data); create a new spreadsheet from scratc",
   "cluster": "content",
   "src": "plugin",
   "mtime": "2026-07-11",
   "depth": 0,
   "latest": null,
   "trigger": "the xlsx in my downloads\\",
   "quiet": false
  }
 ],
 "timeline": [
  {
   "date": "2026-07-15",
   "skill": "bb-deck-builder",
   "cluster": "content",
   "summary": "REAL LOGOS, not typed names (Waverley ICP)"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-deck-builder",
   "cluster": "content",
   "summary": "BREATHE, do not cram (Waverley ICP - the #1 fix)"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-deck-builder",
   "cluster": "content",
   "summary": "MATCH THE BRAND WEIGHT, not your house style (Waverley ICP)"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-deck-builder",
   "cluster": "content",
   "summary": "HEADER CLUTTER on repeated slides (Waverley ICP)"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-deck-builder",
   "cluster": "content",
   "summary": "THE ROOT CAUSE: no per-slide pixel check"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "ELEVATED bb-web-seo-foundation (Fable) + Sastho proof retrofit: THE SUBPATH TRAP and THE WHATSAPP STANDARD"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "\"Make it look like an Apple designer made it\" = REMOVE the decoration, add material depth; the accent glow was the cheap thing (worse in lig"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "CCT round 9: dedup CTAs, and reuse the retired section's asset"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "\"Looks so AI\" = the eyebrow dash; the ambient glow must be BIG or it reads as a smudge; born the bb-anti-ai-tells skill"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "CCT round 8: \"move it left / move it right\" is usually a too-narrow centered container, not per-element nudges"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Dev OS premium pass #2 (density + hierarchy + signature): \"premium\" is loud space and loud hierarchy, not quiet minimalism"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "CCT round 7: stitch client videos with ffmpeg into a web video band; and \"dashes = AI vibes\" means the decorative label accent line"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "CCT round 6: hero-copy vs sticky-nav collision, overlapping card deck, and NEVER gate visibility on requestAnimationFrame"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "CCT round 5: client-supplied AI photos wired into the hero; convert PNG→JPG with `sips` before shipping"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "CCT round 4: scroll-down polish = one photo CTA band; and never add a scrim on `::before` if the element already uses it"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "CCT round 3: \"homepage\" meant the HERO, and a travel DMC's imagery must be GLOBAL not host-country-only"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "\"Make everything perfect\" = a real QA sweep + house-style enforcement, not invented rework"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Dev OS login rebuilt to the Video System pattern: real logo + username/password + sidebar clock, and the \"logo lives in the login AND the le"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "CCT round 3: \"homepage/start page\" meant the HERO itself, not a section below it (+ the var() token that silently zeroed padding)"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "CCT round 2: \"blue and yellow logo\" meant two-tone (both brand colours), + a mood-filter section from EXISTING photos"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "BB SYSTEM DESIGN STANDARD v2 locked (self-audit of my own \"premium pass\" against Linear/Vercel/Stripe)"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Sales Playbook inside the Leads System: reference content becomes a feature when it surfaces AT the moment of use"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "CCT website truth-pass + hero-entrance animation trap + Downloads can't be served"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Dev OS premium pass: the flagship feel is 5 specific objects, all derived, none new-data"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "BUILT BB Dev OS (bb-dev-system): the four-gearset board, and stages-as-config with a meta-stage map is how one board carries four kinds of w"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Sapphire Trails light-luxury reskin: the \"too dark\" fix + silent-patch trap"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Footer giant-icon regression + theme-flip footer trap (Sapphire Trails, client caught it)"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "AUDIT EVERY ICON by rendering it, don't trust the path name (Sapphire Trails)"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "All-ivory scroll reads \"boring\"; break it with ONE dramatic dark section + on-brand accent colour"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Sapphire-blue as the interactive/hover accent on a gold-primary luxury site; and CSSOM > headless getComputedStyle"
  },
  {
   "date": "2026-07-15",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Toggle switch that \"doesn't work\": a stopPropagation on the control ate its own click"
  },
  {
   "date": "2026-07-14",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Graphic Pipeline in CC + v2 skin ported to all 4 satellite systems"
  },
  {
   "date": "2026-07-14",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "BUILT bb-backlink-engine (Fable): links are LEADS, and the NAP poison gate caught a real three-way contact conflict live"
  },
  {
   "date": "2026-07-14",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "HERO COPY GOES IN A LEFT COLUMN, never full-width (recurring Thulaib note)"
  },
  {
   "date": "2026-07-14",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Hero video = a MONTAGE of the client's clips, not one clip; and override placement"
  },
  {
   "date": "2026-07-13",
   "skill": "bb-blog-pack-builder",
   "cluster": "content",
   "summary": "Sapphire Trails, 8-post SEO/AEO/GEO pack (first build)"
  },
  {
   "date": "2026-07-13",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Command Centre v2 modernization (12.5k lines, live system): the reskin playbook"
  },
  {
   "date": "2026-07-13",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "BUILT the blog-ranking engine (bb-blog-engine + bb-seo-geo-blog-plus), Fable pass: the unit of SEO work is the CLUSTER, and the -plus layer "
  },
  {
   "date": "2026-07-11",
   "skill": "bb-content-plan-builder",
   "cluster": "content",
   "summary": "Fixing baked-in text on raster graphics (SAPHIRE -> SAPPHIRE, 11 images)"
  },
  {
   "date": "2026-07-11",
   "skill": "bb-content-plan-builder",
   "cluster": "content",
   "summary": "QA pass caught brand errors baked into the client's graphics (Sapphire Trails)"
  },
  {
   "date": "2026-07-10",
   "skill": "bb-content-plan-builder",
   "cluster": "content",
   "summary": "Sapphire Trails, July plan (first build, 12 posts)"
  },
  {
   "date": "2026-07-10",
   "skill": "bb-ditto",
   "cluster": "systems",
   "summary": "playzone-marketing-dna.md (marketing domain, from the real Jun-2026 scan) - the"
  },
  {
   "date": "2026-07-10",
   "skill": "bb-ditto",
   "cluster": "systems",
   "summary": "REVERSE-DITTO on BB itself (test run #2 of the skill)"
  },
  {
   "date": "2026-07-10",
   "skill": "bb-system-forge",
   "cluster": "systems",
   "summary": "RESTAURANT VERTICAL MOLD BUILT (archetype 3, on Fable)"
  },
  {
   "date": "2026-07-10",
   "skill": "bb-system-forge",
   "cluster": "systems",
   "summary": "RECEIPT RAIL BUILT into the master skeleton (Fable, the GaaS foundation)"
  },
  {
   "date": "2026-07-10",
   "skill": "bb-system-forge",
   "cluster": "systems",
   "summary": "THE 3 DIGITAL-STAFF AGENTS BUILT (Fable, completes the GaaS engine)"
  },
  {
   "date": "2026-07-10",
   "skill": "bb-vertical-blueprint",
   "cluster": "systems",
   "summary": "restaurant — first blueprint (method proof run)"
  },
  {
   "date": "2026-07-10",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Waterman (WESPL) single-page → 5-page conversion"
  },
  {
   "date": "2026-07-10",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "(restaurant mold, Fable): a NEW VERTICAL on the master skeleton = add a module SECTION + redefine FLOOR_MODULES, never carve out the old cor"
  },
  {
   "date": "2026-07-10",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "BB cinematic homepage (Fable) - the storefront that IS the portfolio"
  },
  {
   "date": "2026-07-10",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "v2 (neon rebuild after honest client pushback): \"restraint\" lost to the BRIEF - when"
  },
  {
   "date": "2026-07-08",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "PORTING the self-test harness into a bespoke demo (Home Depot): adapt the checks to the app's real API, don't copy skeleton internals"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "SELF-TEST HARNESS in the skeleton: in-app tests with snapshot/restore, pristine-markup blank detection, and testing the safety nets themselv"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Live accent recolour from ONE picker: override CSS vars on documentElement.style"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "A client demo's \"custom section\" = a Customization Studio wired to REAL state, not the skeleton's config engine"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Turn an inventory LIST into a DECISION tool: analytics strip + Kanban + views (what a manager/CEO actually asks)"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "A generic `.search{display:none}` mobile rule silently hides ANY new in-page input that reuses the class"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Reskinning a config-driven skeleton is a Python builder + a seed generator, not hand-editing; verify the DATA offline first"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Porting a master-skeleton module into a live app = ADAPT to the host's conventions, never paste"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "A ported global that collides with an existing `const` breaks the WHOLE script silently"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Reversible \"convert to order\" with inventory auto-decrement (one bundled undo)"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "CUSTOMIZATION STUDIO in the master skeleton: overrides-over-snapshot config, sanitize-on-apply as the security boundary, chrome-as-function"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Porting a proven module into a LIVE system: clone the host's native insert shape, and make auto-map survive labels with hint text"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Client-side image compression to a Storage URL (NEVER base64), reversible-side-effect hooks, and offline-first spreadsheet import"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Consolidating two sibling pages: fold the extra nav item into a tab, and make the merged view answer the question the split couldn't"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "\"Classless\" pie labels: the tell is the black text-outline. Premium = contrast-aware fill, no stroke, + a center hero number"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Headless-preview screenshots break on a SCROLLED sticky header (topbar renders at the bottom, content blank); trust the DOM rect + config in"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Consolidating a \"feature floor\" into a skeleton: derive analytics from real data, gate modules by CFG flag, add the container before the ren"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Adding PIN login + a master \"see everyone\" view to a static single-file site = Supabase RPC-only auth (no Supabase Auth); the pattern, and t"
  },
  {
   "date": "2026-07-07",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Analytics: compare COMPLETED periods, and any \"collected vs expected\" rate must share one roster basis"
  },
  {
   "date": "2026-07-06",
   "skill": "bb-motion-master",
   "cluster": "web",
   "summary": "All 5 BB industry templates shipped: ONE motion substrate, 5 art directions"
  },
  {
   "date": "2026-07-06",
   "skill": "bb-motion-master",
   "cluster": "web",
   "summary": "Tuition starter template (mold #1 of the BB template line)"
  },
  {
   "date": "2026-07-06",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "BB OS ACADEMY shipped LIVE (all 27 remaining quizzes + deploy) — the em-dash rule vs. verbatim doc quotes, and the two-model handoff worked "
  },
  {
   "date": "2026-07-06",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "BB OS ACADEMY (~/bb-websites/bb-os-academy/) — internal learning-site pattern: parse-don't-hardcode + a quiz layer that survives re-sync — E"
  },
  {
   "date": "2026-07-06",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "THE 5 BB INDUSTRY WEBSITE STARTER TEMPLATES ARE COMPLETE (~/bb-web-templates/) — the reusable template line"
  },
  {
   "date": "2026-07-06",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "MASTER SYSTEM SKELETON built (~/bb-systems/master-skeleton/bb-master-skeleton.html) — derive brand tokens, gate by data-attributes, never le"
  },
  {
   "date": "2026-07-06",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "TUITION STARTER TEMPLATE (mold #1, ~/bb-web-templates/tuition/) — ELEVATED CHOICES + FABLE vs BASELINE"
  },
  {
   "date": "2026-07-05",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Adding a \"smart layer\" is cheap value; charts need theme-aware destroy+recreate + graceful CDN fallback"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-growth-sales",
   "cluster": "sales",
   "summary": "Leon/BSWL — the service-to-system upsell ladder is real"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-growth-sales",
   "cluster": "sales",
   "summary": "Leon/BSWL — speed of a live demo closes"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-motion-master",
   "cluster": "web",
   "summary": "BSWL (Leon) site: first client build on the skill"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-motion-master",
   "cluster": "web",
   "summary": "Skill founding build (reference extraction + first demo)"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Client demos stay FRONT-END ONLY until the client confirms the backend (Thulaib's rule)"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Context-aware toolbar action for merged toggle views"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Demo \"current date\" must have ONE source, or the top bar and dashboard disagree"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Merge two related views into one page with a segmented toggle, not two nav items"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "World-class completeness = trust strip + how-to-enrol + FAQ, all honest (BSWL)"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "A site with NO people reads as cold/unfinished, even at high craft (BSWL students wall)"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Every flagship BB site needs a SMART FEATURE, not just a pretty scroll (BSWL finder)"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "`[hidden]` attribute loses to any class rule that sets `display` — add a global override"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Month-by-month revenue recognition grid (SalesOS flagship finance screen)"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Wide editable grid on mobile: scroll the CARD, not the page"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Consolidating a bloated nav by MERGING views into tabs/toggles, not deleting them"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Expanding a single-file system to role-based multi-view: extend the DB, gate the nav, dispatch renderers"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "\"Self missing\" in a team/roster view = current user not in the roster array"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Headless preview: CSS transitions do NOT advance between evals — \"stuck\" transforms are phantom bugs"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "BSWL system reskin: invert a monochrome brand in dark mode via ONE --on-accent token"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "BSWL website W2+W3 (full build) — ELEVATED CHOICES + facts discipline"
  },
  {
   "date": "2026-07-04",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "BSWL website W1 (scaffold) — ELEVATED CHOICES"
  },
  {
   "date": "2026-07-03",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "iOS clips content on the right edge (page renders too wide) = missing text-size-adjust. PUT IT IN EVERY SYSTEM."
  },
  {
   "date": "2026-07-03",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Mobile login card jams / logo clips when the iOS keyboard opens — use margin:auto + scroll"
  },
  {
   "date": "2026-07-03",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Clean multi-page PDF export: paginate by whole blocks, never slice one tall canvas"
  },
  {
   "date": "2026-07-03",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "html2canvas is unusably slow/hangs in the Claude_Preview headless env on complex blocks"
  },
  {
   "date": "2026-07-03",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Theme-aware footer/brand logo: reuse existing on-page logo srcs, don't hardcode base64 twice"
  },
  {
   "date": "2026-07-03",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "BB DESIGN SYSTEM v1 (master skeleton, reuse on every client system)"
  },
  {
   "date": "2026-07-03",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Chart.js dark mode: Chart.defaults.color is not enough"
  },
  {
   "date": "2026-07-03",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Chart.js doughnut: use chartjs-plugin-datalabels for segment labels"
  },
  {
   "date": "2026-07-03",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Doughnut charts need explicit container height, not canvas height attribute"
  },
  {
   "date": "2026-07-02",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Quarter comparison delta must use monthly average, not raw total"
  },
  {
   "date": "2026-07-02",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Login flow: pickUser + doLogin needs the password field set between calls"
  },
  {
   "date": "2026-07-02",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "QA integration pass: lost-stage exclusion is a full-repo grep, not a one-spot fix"
  },
  {
   "date": "2026-07-02",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Chart.js data arrays must match the filtered stage list"
  },
  {
   "date": "2026-07-02",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Probability dropdown must include 0% for any stage that uses prob:0"
  },
  {
   "date": "2026-07-02",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Follow-up due today: sort follow-ups to the top of the queue, not just mixed in"
  },
  {
   "date": "2026-07-02",
   "skill": "bb-web-master",
   "cluster": "web",
   "summary": "Login in preview: field IDs changed (lgPw not pin), use doLogin() directly"
  }
 ],
 "undatedCount": 72,
 "totals": {
  "skills": 109,
  "entries": 187,
  "datedEntries": 115,
  "clusters": 8,
  "depthByCluster": {
   "web": 147,
   "seo": 0,
   "sales": 6,
   "strategy": 0,
   "content": 9,
   "ads": 0,
   "systems": 25,
   "intel": 0
  }
 }
};
